run:
  concurrency: 4
  deadline: 3m
  issues-exit-code: 0
  tests: true
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: false
                               
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - interfacer
    - scopelint
    - nosnakecase
    - ifshort
    - structcheck
    - deadcode
    - exhaustivestruct
    - golint
    - maligned
    - varcheck
    - gci
    - nolintlint
  fast: false

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  misspell:
    locale: US
